version: '3'
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 49153:49153
    container_name: frontend
    volumes:
       - ./frontend/:/usr/src/app
       - /usr/src/app/node_modules
  
  server:
    build:
      context: ./backend/
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: mongoose
    volumes:
      - ./backend/:/app
      - /app/node_modules
    restart: 'unless-stopped'
    links:
      - mongo
    depends_on:
      - mongo
  
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - '27017:27017'

volumes:
  data:
    driver: local
